
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vm.box = "ubuntu/xenial64"
    
    config.vm.provision "shell", privileged: true, inline: <<-SHELL
        apt-get update
        apt-get install software-properties-common
        apt-add-repository ppa:ansible/ansible
        apt-get update
        apt-get install -y ansible
    SHELL
end